server:
  port: 8101

spring:
  application:
    name: bookservice
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8500/sso/oauth2/jwks
  datasource:
    url: jdbc:mysql://localhost:3306/cloudstudy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: niuniu0626
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.common.entity

