server:
  port: 8301

spring:
  application:
    name: borrowservice
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: lbwnb
  datasource:
    url: jdbc:mysql://localhost:3306/cloudstudy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: niuniu0626
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ephemeral: false
        cluster-name: Chengd
    loadbalancer:
      nacos:
        enabled: true
    sentinel:
      transport:
        # 添加监控页面地址即可
        dashboard: localhost:8858
      block-page: /borrow/blocked

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.common.entity

